### Get tasks
GET http://localhost:3001/

### Add new task
POST http://localhost:3001/new
Content-Type: application/json

{
    "description": "1 from Dipendra"
}

### Delete task
DELETE http://localhost:3001/delete/12 HTTP/1.1
